global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]
    scheme: http
#      insecure_skip_verify: true
#    basic_auth:
#      username: siem
#      password: Interface3
